version: '3'
services:
    db2:
      image: kartoza/postgis:9.6-2.4
      container_name: postgres_for_nearby
      environment:
        - POSTGRES_DB=my_db
        - POSTGRES_USER=user2
        - POSTGRES_PASSWORD=123456789
        - ALLOW_IP_RANGE=0.0.0.0/0

      ports:
        - 5435:5435
      command: postgres -c listen_addresses='*'
      restart: unless-stopped
      volumes:
        - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
        - ./Datafiniti_Fast_Food_Restaurants_May19.csv:/Datafiniti_Fast_Food_Restaurants_May19.csv
        - ./database-data:/var/lib/postgresql/data/ # persist data even if container shuts down                                                                  
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db2
volumes:
  database-data: # named volumes can be managed easier using docker-compose        